runMode: debug
addr: :8080

db:
  host: 10.0.0.5
  username: root
  password: root
  database: evo-blog
  max-idle-connections: 100
  max-open-connections: 100
  max-connection-life-time: 10s
  log-level: 4

log:
  disableCaller: false
  disableStacktrace: false
  level: debug
  format: console
  outputPaths: [ /tmp/evo-blog-gf.log, stdout ]